query getCurrentUser {
  getCurrentUser {
    data {
      avatar
      createdAt
      email
      emailVerified
      firstName
      forgotPasswordLock
      id
      lastName
      name
      phoneNumber
      phoneNumberVerified
      twoFactorVerified
    }
    errors {
      message
      path
    }
    success
  }
}
