query getMyContacts($Pagination: PaginationInputType) {
  getMyContacts(Pagination: $Pagination) {
    data {
      avatar
      createdAt
      email
      emailVerified
      firstName
      forgotPasswordLock
      id
      lastName
      name
      phoneNumber
      phoneNumberVerified
      twoFactorVerified
      username
    }
    errors {
      message
      path
    }
    success
  }
}
