query getBankAccount($data: GetBankAccountDto!){
    getBankAccount(data: $data){
        data{
            accountId
            ach{
                account
                id
                routingNumber
                wire_routing
            }
            addedAt
            balance{
                availableBalance
                currentBalance
                id
                isoCurrencyCode
                limitBalance
                unofficialCurrencyCode
            }
            id
            institution{
                institutionId
                institutionLogo
                institutionName
                primaryColor
                websiteUrl
            }
            name
            officialName
            subType
            type
            userId
        }
        errors{
            message
            path
        }
        success
    }
}