query getMyBtcAddress() {
    getMyBtcAddress{
        data{
            chainInvoice{
                address
                createdAt
                id
                userId
            }
            lightningInvoice{
                addIndex
                createdAt
                expiresAt
                id
                payReq
                rHash
                userId
            }
        }
        errors{
            message
            path
        }
        success
    }
}