query getNodeTransactions($Pagination: PaginationInputType) {
    getNodeTransactions(Pagination: $Pagination){
        data{
            amount
            blockHash
            fees
            hash
            timeStamp
        }
        errors{
            message
            path
        }
        success
    }
}