query getPaymentRequest($data: GetPaymentRequestDto!) {
    getPaymentRequest(data: $data){
        data{
            createdAt
            expiredAt
            id
            requestFrom
            requestTo
            settledAt
            status
            transaction{
                amount
                amountLessFee
                btcAmount
                btcExchangeRate
                createdAt
                currency
                description
                fromWalletId
                id
                method
                networkFee
                paidAmount
                settledAt
                status
                toWalletId
                transactionFee
            }
        }
        errors{
            message
            path
        }
        success
    }
}