query getPaymentRequests($Pagination: PaginationInputType){
    getPaymentRequests(Pagination: $Pagination){
        data{
            createdAt
            expiredAt
            id
            requestFrom
            requestTo
            status
            transaction{
                amount
                btcAmount
                btcExchangeRate
                createdAt
                currency
                description
                fromWalletId
                id
                method
                networkFee
                status
                toWalletId
                transactionFee
            }
        }
        errors{
            message
            path
        }
        success
    }
}