export const STORAGE_KEY = {
  ACCESS_TOKEN: `ACCESS_TOKEN`,
  REFRESH_TOKEN: `REFRESH_TOKEN`,
  TRANSACTIONS: `TRANSACTIONS`,
  CURRENT_USER: `CURRENT_USER`,
  MY_WALLET: `MY_WALLET`,
  REQUESTED_TRANSACTIONS: `REQUESTED_TRANSACTIONS`,
  CONTACTS: `CONTACTS`,
  BANK_ACCOUNTS: `BANK_ACCOUNTS`,
}
