query getMyWalletTransactions($Pagination: PaginationInputType) {
  getMyWalletTransactions(Pagination: $Pagination) {
    data {
      amount
      btcAmount
      btcExchangeRate
      createdAt
      currency
      description
      fromWalletId
      id
      method
      networkFee
      status
      toWalletId
      transactionFee
    }
    errors {
      message
      path
    }
    success
  }
}
