query getWallet($data: GetWalletDto!) {
  getWallet(data: $data) {
    data {
      balance
      createdAt
      defaultCurrency
      id
      userId
    }
    errors {
      message
      path
    }
    success
  }
}
